package Runners;

import org.junit.Test;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.concurrent.BlockingQueue;
import java.util.concurrent.LinkedBlockingQueue;

import static org.junit.Assert.assertEquals;


public class TestWriter {
    /**
     * Test to check that what is inside the input queue ends in the correct position in the csv file
     */
	@Test
    public void Test() throws IOException {
        BlockingQueue<int[]> outQueue = new LinkedBlockingQueue<int[]>();
        outQueue.add(new int[]{0, 9, 10, 2, 8, 10, 2, 7, 4});
        outQueue.add(new int[]{1, 10, 10, 0,9, 10, 2,8, 10});
        outQueue.add(new int[]{2, 11, 10, 1,10, 10, 0,9, 10});
        outQueue.add(new int[]{1, 12, 10, 2,11, 10, 1,10, 10});
        outQueue.add(new int[]{0, 13, 10, 1,12, 10, 2,11, 10});
        outQueue.add(new int[]{0, 14, 10, 0,13, 10, 1,12, 4});
        outQueue.add(new int[]{1, 15, 10, 0,14, 10, 0,13, 4});
        outQueue.add(new int[]{2, 16, 10, 1,15, 10, 0,14, 4});
        outQueue.add(new int[]{1, 17, 10, 2,16, 10, 1,15, 10});
        outQueue.add(new int[]{1, 18, 10, 1,17, 10, 2,16, 10});
        outQueue.add(new int[]{0, 19, 10, 1,18, 10, 1,17, 10});
        //poison-pill
        outQueue.add(new int[]{-1});

        Writer writer = new Writer(outQueue);
        writer.run();

        //Read the csv file generated by Writer and compare it to testData20
            // Open data files
                // Data generated by write
        FileReader generatedDataReader = new FileReader("src/main/resources/data.csv");
        BufferedReader generatedDataBuffer = new BufferedReader(generatedDataReader);
                // test data
        FileReader testDataReader = new FileReader("src/main/resources/testData20.csv");
        BufferedReader testDataBuffer = new BufferedReader(testDataReader);

        // Test if the files are identical
        String generatedDataLine = generatedDataBuffer.readLine();
        String testDataLine = testDataBuffer.readLine();
        while (generatedDataLine != null || testDataLine != null) {
            assertEquals(generatedDataLine, testDataLine);
            generatedDataLine = generatedDataBuffer.readLine();
            testDataLine = testDataBuffer.readLine();
        }

        // Close files
        generatedDataBuffer.close();
        generatedDataReader.close();
        testDataBuffer.close();
        testDataReader.close();
    }
}