import static org.junit.Assert.*;
import org.junit.Test;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;


public class TestMain {
    /**
     * We call {@link Main#process(String)} on the 5000 data directory and then compare the resulting data.csv
     * with a testData.csv generated by the mos brutal method that we hope works correctly.
     */
    @Test
    public void process() throws IOException {
        Main.process("data\\5000");
        // Open data files
            // Data generated by process
        FileReader generatedDataReader = new FileReader("src/main/resources/data.csv");
        BufferedReader generatedDataBuffer = new BufferedReader(generatedDataReader);
            // test data
        FileReader testDataReader = new FileReader("src/main/resources/testData.csv");
        BufferedReader testDataBuffer = new BufferedReader(testDataReader);

        // Test if the files are identical
        String generatedDataLine = generatedDataBuffer.readLine();
        String testDataLine = testDataBuffer.readLine();
        while (generatedDataLine != null || testDataLine != null) {
            assertEquals(generatedDataLine, testDataLine);
            generatedDataLine = generatedDataBuffer.readLine();
            testDataLine = testDataBuffer.readLine();
        }

        // Close files
        generatedDataBuffer.close();
        generatedDataReader.close();
        testDataBuffer.close();
        testDataReader.close();
    }
}